### ISSUE TITLE
How To Print Barcode with characters ?

### ISSUE THREAD

**Issue by mjafartp** [andrey-ushakov/esc_pos_utils#16]
How to print barcode with characters

need to Print A12345

**Comment by Dshosev** [comment]
@mjafartp this is easily done within your ticket with the following code:

```
// ...
  ticket.barcode(Barcode.code39(['A', 1, 2, 3, 4, 5]));
// ...
```

Note, that code39 is not the only applicable type of barcodes. You can find more, with explanation under the following link:
[Types of Barcodes: Choosing the Right Barcode](https://www.scandit.com/de/blog/types-barcodes-choosing-right-barcode/)

So, if your Barcode will be in the fixed format "A12345", then you can use code39, and give it the List of data to be printed as parameter.

If you have any further Questions, don't hesitate to answer in this issue.
Otherwise it would be cool to close this (@andrey-ushakov).

Best Regards
Dsv

**Comment by Dshosev** [comment]
I think this could be closed then? @mjafartp
